
language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.4" 
services:
  - postgresql
  
before_script:
  - psql -c "CREATE DATABASE bancoSistex;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'ifes';" -U postgres
